#!/usr/bin/python
#
#   Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...    
#   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
#

import sys

def main():
    fib = [0,1]    
    belowFourMillion = True
    i = 2
    finalSum = 0
    while(belowFourMillion):
        newTerm = sum([fib[i-1], fib[i-2]])
        fib.append(newTerm)
        if(newTerm % 2 == 0):
            finalSum += newTerm
            print("Final Value: " + str(finalSum))
        i = i + 1
        if(newTerm > 4000000): 
            belowFourMillion = False    
    print(finalSum)

if __name__ == '__main__':
  main()